# Page settings
baseurl = "localhost:1313"
title = "MonBelOrdi"
languageCode = "fr-fr"
theme = "elate"

[params]

  custom_css = ["css/2017_10_08_font.css"]

  # Meta
  author = "Alain Sanguinetti"
  description = "Réglez vos problèmes informatiques"
  email = "contact@monbelordi.fr"
  # Navigation
  [params.navigation]
    brand = "MonBelOrdi"
    home = "Accueil"
    # work = "Work"
    testimonials = "Témoignages"
    services = "Expertise"
    about = "A propos"
    contact = "Contact"

    # You can add custom links before or after the default links
    # Assign a weight to define the order

    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10

    # postpended links
    #[[menu.postpend]]
    #  url = "http://gohugo.io"
    #  name = "External link"
    #  weight = 10

  # Hero section
  [params.hero]
    title = "Aimez vos outils informatiques"
    subtitle = 'Ils nous simplifient la vie, nous permettent de communiquer avec le monde entier, ils sont indispensables. Laissez-nous vous les faire aimer.'

  # Intro section
  # Available icons: http://simplelineicons.com/
  [params.intro]

  [[params.intro.item]]
    title = "Choix"
    description = "Dans la vie, il y a les appareils qui ont l’air bien, ceux qui sont bien et ceux qui en plus sont en promo ! Mais tout ça dépend de vos besoins, alors passons-les en revue ensemble."
    url = "#contact"
    button = "Prendre rendez-vous"
    icon = "icon-bulb"
    img = "img_7.jpg"

  [[params.intro.item]]
    title = "Cours"
    description = "En informatique, on a toujours quelque chose à apprendre ! Et vous, qu’allez-vous apprendre aujourd’hui ?"
    url = "#contact"
    button = "Je veux progresser"
    icon = "icon-rocket"
    img = "img_8.jpg"

  [[params.intro.item]]
    title = "Dépannage"
    description = "Tout n’est pas perdu! Contactez-nous pour voir ce que vous pouvez récupérer : le matériel, les données, les réglages. Pas de gestes précipités, contactez-nous d’abord."
    url = "#contac"
    button = "J’appelle le médecin"
    icon = "icon-wrench"
    img = "img_10.jpg"

  [params.intro.video]
    enable = false
    title = "Watch the video"
    icon = "icon-play2"
    url = "https://vimeo.com/channels/staffpicks/93951774"


  # Work section
  [params.work]
    enable = false
    title = "Work"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."
    footertext = '** Demo images from <a href="http://plmd.me/" target="_blank">plmd.me</a>'

    [[params.work.row]]
      img = "work_1.jpg"
      alt = "Image2"
      title = "Project 1"
      subtitle = "Branding"

    [[params.work.row]]
      img = "work_2.jpg"
      alt = "Image2"
      title = "Project 2"
      subtitle = "Design"

    [[params.work.row]]
      img = "work_3.jpg"
      alt = "Image3"
      title = "Project 3"
      subtitle = "Design"

    [[params.work.row]]
      img = "work_4.jpg"
      alt = "Image4"
      title = "Project 4"
      subtitle = "Design"

    [[params.work.row]]
      img = "work_5.jpg"
      alt = "Image5"
      title = "Project 5"
      subtitle = "Design"

    [[params.work.row]]
      img = "work_6.jpg"
      alt = "Image6"
      title = "Project 6"
      subtitle = "Design"

  # Testimonials section
  [params.testimonials]
    enable = false
    title = "Témoignages"
    description = "Ce sont nos clients qui parlent le mieux de nous."

    [[params.testimonials.item]]
      quote = "&ldquo;Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean.&rdquo;"
      person = 'Jean Doe, CEO <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> <span class="subtext">Creative Director</span>'
      img = "person1.jpg"
      alt = "Person1"

    [[params.testimonials.item]]
      quote = "&ldquo;Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean. Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.&rdquo;"
      person = 'John Doe, Senior UI <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> <span class="subtext">Creative Director</span>'
      img = "person2.jpg"
      alt = "Person2"

    [[params.testimonials.item]]
      quote = "&ldquo;Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. &rdquo;"
      person = 'Chris Nash, Director <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> <span class="subtext">Creative Director</span>'
      img = "person3.jpg"
      alt = "Person3"




  # Services section
  [params.services]
    enable = true
    title = "Expertise"
    description = "Nous sommes des professionnels."

    [[params.services.item]]
    title = "Système"
    description = "Mac, Windows, Linux, Mainframe, nous sommes à l’aise sur tous les environnements informatiques."
    icon = "icon-monitor"

    [[params.services.item]]
      title = "Pédagogie"
      description = "Nous avons appris à des personnes agées de 90 ans à insérer des images dans un document."
      icon = "icon-anchor"

    [[params.services.item]]
      title = "Sécurité"
      description = "Nous connaissons les dangers de l’informatique et les ripostes associées."
      icon = "icon-layers2"

    [[params.services.item]]
      title = "Analyse du besoin"
      description = "Nous pouvons vous aider à choisir un appareil, en fonction de vos critères exprimés et des critères que nous connaissons, qui ferons que vous serez pleinement satisfaits."
      icon = "icon-video2"


  # About section
  [params.about]

    # See about.html to configure an appropriate offset
    enable = true
    title = "A propos"
    description = "Voici qui se cache derrière la marque « MonBelOrdi »"

    [[params.about.item]]
      name = "Alain Sanguinetti"
      position = "Ingénieur en informatique"
      description = "Je suis tombé dans la marmite de l’informatique quand j’étais petit .."
      img = "person2.jpg"
      alt = "Person2"
      social = [
        ["icon-twitter", "https://www.twitter.com/al1sangui"],
        ["icon-facebook", "https://www.facebook.com/alain.sanguinetti"],
        ["icon-github", "https://github.com/alainsanguinetti"]
      ]
    #
    # [[params.about.item]]
    #   name = "Larry Ben"
    #   position = "Web Designer"
    #   description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts"
    #   img = "person3.jpg"
    #   alt = "Person3"
    #   social = [
    #     ["icon-twitter", "#"],
    #     ["icon-facebook", "#"],
    #     ["icon-dribbble", "#"]
    #   ]

  # Counters section
  [params.counters]
    enable = true
    title = "Stats"
    background = "full_image_1.jpg"

    [[params.counters.item]]
      description = "Interventions"
      icon = "icon-briefcase"
      from = 0
      to = 42
      interval = 3
      speed = 5000

    [[params.counters.item]]
      description = "Heures"
      icon = "icon-code"
      from = 0
      to = 72
      interval = 3
      speed = 5000

    [[params.counters.item]]
      description = "Clients satisfaits"
      icon = "icon-cup"
      from = 0
      to = 42
      interval = 3
      speed = 5000

  # Contact section
  [params.contact]
    enable = true
    map = false
    title = "Contactez-nous"
    description = "Nous sommes à votre écoute."

    # Available icons: http://simplelineicons.com/
    details = [
        ["icon-home", "241 rue de Charenton, B/3D, 75012 PARIS"],
        ["icon-phone", "+33 7.70.03.56.46"],
        ["icon-envelope", "contact@monbelordi.fr"],
        # ["icon-globe", '<a href="http://freehtml5.co/" target="_blank">freehtml5.co</a>']
      ]

    name = "Nom"
    email = "Email"
    phone = "Téléphone"
    message = "Message"
    button = "Envoyer"

  # Footer section
  [params.footer]
    enable = true
    copyright = '&copy; Elate Free HTML5. All Rights Reserved. <br>Created by <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> Images: <a href="http://pexels.com/" target="_blank">Pexels</a>, <a href="http://plmd.me/" target="_blank">plmd.me</a> <br>Hugo port by: <a href="https://github.com/saey55" target="_blank">saey55</a>'
